name: Generate Commit Report

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: true
        type: string
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: true
        type: string
      username:
        description: 'Specific user (optional)'
        required: false
        type: string
      format:
        description: 'Report format'
        required: true
        type: choice
        options:
          - excel
          - csv
        default: excel

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install boto3 pandas openpyxl python-dateutil

      - name: Generate Report
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          python generate_report.py \
            --start-date "${{ inputs.start_date }}" \
            --end-date "${{ inputs.end_date }}" \
            --username "${{ inputs.username }}" \
            --format "${{ inputs.format }}"

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: commit-report-${{ inputs.start_date }}-to-${{ inputs.end_date }}
          path: report.*
          retention-days: 30