name: retro_load_commits

on:
  workflow_dispatch:
    inputs:
      since:
        description: 'Data/hora inicial ISO (ex: 2025-06-01T00:00:00Z)'
        required: true
        type: string
      until:
        description: 'Data/hora final ISO (ex: 2025-09-01T00:00:00Z)'
        required: true
        type: string
      repo_filter:
        description: 'Filtro simples de nome de repo (contém, opcional)'
        required: false
        type: string
      max_repos:
        description: 'Limitar qtd de repos para teste (0 = sem limite)'
        required: false
        default: '0'
        type: string

permissions:
  contents: read
  actions: read
  id-token: write  # OIDC p/ AWS

env:
  GH_ORG: my-org
  AWS_REGION: us-east-1
  S3_BUCKET: your-bucket-name
  S3_PREFIX: github/commits
  PYTHONUNBUFFERED: "1"

jobs:
  retro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install boto3 requests

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/github-oidc-uploader
          aws-region: ${{ env.AWS_REGION }}

      - name: Run collector
        uses: actions/setup-python@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_READ_ORG }}
          OWNER: ${{ env.GH_ORG }}
          SINCE: ${{ inputs.since }}
          UNTIL: ${{ inputs.until }}
          REPO_FILTER: ${{ inputs.repo_filter }}
          MAX_REPOS: ${{ inputs.max_repos }}
          S3_BUCKET: ${{ env.S3_BUCKET }}
          S3_PREFIX: ${{ env.S3_PREFIX }}

